services:
  backend:
    image: xoriax/umir-backend:latest
    build:
      context: ./back
      dockerfile: ./Dockerfile
  frontend:
    image: xoriax/umir-frontend:latest
    build:
      context: ./front
      dockerfile: ./Dockerfile
